version: "3.9"

x-env: &env
  BUNDLE_PATH: /bundle
  EDITOR: /usr/bin/vim
  REDIS_URL: redis://redis:6379/1
  DATABASE_URL: postgres://postgres:password@postgres:5432/beast_mode_development

x-app: &app
  build: .
  image: hopsoft/beast_mode
  working_dir: /beast_mode
  tty: true
  stdin_open: true
  environment: *env
  networks:
    - main
  volumes:
    - ./:/beast_mode:cached
    - bundle:/bundle:delegated
    - unsynchronized:/beast_mode/log:delegated
    - unsynchronized:/beast_mode/tmp:delegated

volumes:
  bundle:
  postgres:
  unsynchronized:

networks:
  main:

services:
  postgres:
    image: postgres:13.2-alpine
    container_name: beast_mode-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - main
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data:delegated

  redis:
    image: redis:6.2-alpine
    container_name: beast_mode-redis
    restart: unless-stopped
    networks:
      - main
    expose:
      - 6379

  shell:
    <<: *app
    container_name: beast_mode-shell
    command: /bin/bash -c "tail -f /dev/null"

  webpack:
    <<: *app
    container_name: beast_mode-webpack
    command: /bin/bash -c "yarn && bin/webpack-dev-server"
    environment:
      <<: *env
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - 3035:3035

  web:
    <<: *app
    container_name: beast_mode-web
    command: /bin/bash -c "bundle && bin/rails db:create db:migrate db:seed && rm -f tmp/pids/server.pid && bin/rails s --binding=0.0.0.0 --port=3000"
    environment:
      <<: *env
      WEBPACKER_DEV_SERVER_HOST: webpack
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
      - webpack
